# Generated by Django 4.2.1 on 2023-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("S", "Shirt"), ("SW", "Sport wear"), ("OW", "Outwear")],
                default="S",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="discount_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                default="P",
                max_length=1,
            ),
        ),
    ]
