# Generated by Django 4.2.1 on 2023-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_item_category_item_discount_price_item_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(default="Producto de prueba"),
        ),
    ]
