# Generated by Django 4.2.1 on 2023-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_item_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(default="Descripcion de prueba"),
        ),
    ]
